apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scully
  labels:
    app: scully
    {{- include "labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: scully
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: scully
  apiGroup: rbac.authorization.k8s.io
