apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scully
  labels:
    app: scully
    {{- include "labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "update", "patch"]

